---
title: "FGR_filter"
author: "Dmitrii"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)

```

# Загружаем исходный набор данных из Excel таблицы
```{r echo=FALSE}

df <- read_csv("data/raw/source.csv")

```

# Исключаем крайние значения по критериям ISUOG 

<!-- <3th percentile == FGR и >97th percentile == macrosomia -->
<!-- Основа для фильтрации данные исследования intergrowth 21 <https://intergrowth21.tghn.org/standards-tools/>  -->

<!-- ВАЖНО - intergrowth21 начинается с 24 недели гестации -->

**!!!Приведён случайный датафрейм df!!!**
```{r}
# Создаём новые колонки для счёта ниже 3 и выше 97перцентиля по весу тела (BW), длине тела (BL) и отношению веса к длине (WLR)
df$BW3Score<-c(NA) #Вес тела 3 перцентиль
df$BW97Score<-c(NA) #Вес тела 97 перцентиль
df$BL3Score<-c(NA) #Длина тела 3 перцентиль
df$BL97Score<-c(NA) #Длина тела 97 перцентиль
df$WLR3Score<-c(NA) #Отношение вес тела : длина тела 3 перцентиль
df$WLR97Score<-c(NA) #Отношение вес тела : длина тела 97 перцентиль

# Считаем для наших данных WLR
df$WLR<-round((df$BodyWeight/df$BodyLength)/10, digits = 2)


# Загружаем данные для сравнения по 3 и 97 перцентилю. Значения соответвуют week+6, т.е максимальное для недли гестации.
intergrowth <- read_csv("data/raw/intergrowthMAX.csv")


#Задаём счёт случаям меньше BodyWeight 3 перцентиля
for(j in 1:nrow(df)){
  for(k in 1:nrow(intergrowth)){
    if(df$gestation[j] == intergrowth$gestation[k] && df$gender[j] == intergrowth$gender[k]){
      if(df$BodyWeight[j] <= intergrowth$BW_3th[k]){
        df$BW3Score[j] <- 1
      } else {
        df$BW3Score[j] <- 0
      }
    }
  }
}


#Задаём счёт случаям больше BodyLength 97 перцентиля
for(l in 1:nrow(df)){
  for(m in 1:nrow(intergrowth)){
    if(df$gestation[l] == intergrowth$gestation[m] && df$gender[l] == intergrowth$gender[m]){
      if(df$BodyWeight[l] >= intergrowth$BW_97th[m]){
        df$BW97Score[l] <- 1
      } else {
        df$BW97Score[l] <- 0
      }
    }
  }
}

#Очистить все Values
rm(list = ls.str(mode = 'numeric'))

#Задаём счёт случаям меньше BodyLength 3 перцентиля
for(j in 1:nrow(df)){
  for(k in 1:nrow(intergrowth)){
    if(df$gestation[j] == intergrowth$gestation[k] && df$gender[j] == intergrowth$gender[k]){
      if(df$BodyLength[j] <= intergrowth$BL_3th[k]){
        df$BL3Score[j] <- 1
      } else {
        df$BL3Score[j] <- 0
      }
    }
  }
}


#Задаём счёт случаям больше BodyLength 97 перцентиля
for(l in 1:nrow(df)){
  for(m in 1:nrow(intergrowth)){
    if(df$gestation[l] == intergrowth$gestation[m] && df$gender[l] == intergrowth$gender[m]){
      if(df$BodyLength[l] >= intergrowth$BL_97th[m]){
        df$BL97Score[l] <- 1
      } else {
        df$BL97Score[l] <- 0
      }
    }
  }
}

#Очистиить все Values
rm(list = ls.str(mode = 'numeric'))


#Задаём счёт случаям меньше WLR 3 перцентиля
for(j in 1:nrow(df)){
  for(k in 1:nrow(intergrowth)){
    if(df$gestation[j] == intergrowth$gestation[k] && df$gender[j] == intergrowth$gender[k]){
      if(df$WLR[j] <= intergrowth$WLR_3th[k]){
        df$WLR3Score[j] <- 1
      } else {
        df$WLR3Score[j] <- 0
      }
    }
  }
}


#Задаём счёт случаям больше WLR 97 перцентиля
for(l in 1:nrow(df)){
  for(m in 1:nrow(intergrowth)){
    if(df$gestation[l] == intergrowth$gestation[m] && df$gender[l] == intergrowth$gender[m]){
      if(df$WLR[l] >= intergrowth$WLR_97th[m]){
        df$WLR97Score[l] <- 1
      } else {
        df$WLR97Score[l] <- 0
      }
    }
  }
}

#Очистиить все Values
rm(list = ls.str(mode = 'numeric'))

# Сложить результаты
df$score <- df$BW3Score + df$BW97Score + df$BL3Score + df$BL97Score + df$WLR3Score + df$WLR97Score

#Удалить все строке в score не содержащие 0
# df <- filter(df, score == 0)

# Удаляем лишние колонки
# df <- df %>% select(-c(BW3Score, BW97Score, score))

```


# Создаём колонки и заполняем расчётные коэффициенты
```{r}
df$BrainLiver <- round(df$brain/df$liver, digits = 1) #BrainLiver =  мозг/печень. Альтенативное выявления FGR
df$PI <- round((df$BodyWeight/df$BodyLength^3)*100, digits = 1) #расчитываем пондеральный индекс (PI). Аналог BMI
df$BMI <- round(((df$BodyWeight/1000)/df$BodyLength^2), digits = 4) 
#df$BSA_Du_Bois <- round(0.007184*(df$BodyWeight^0.425/1000)*df$BodyLength^0.725)) # Что-то напутал со скобками. Оригинал формулы BSA = 0.007184 × W^0.425 × H^0.725 W в килограммах 

df$BSA_Du_Bois <- round((71.84*df$BodyWeight^0.425*df$BodyLength^0.725), digits = 1) #Модифицированная из статьи Ahn PMID 21874709
df$BSA_Boyd <- round((4.688*df$BodyLength^(0.8168-0.0154*log(df$BodyWeight))), digits = 1) #Модифицированная из статьи Ahn PMID 21874709
df$BSA_neo <-  round((5.52005*df$BodyWeight^0.5526*df$BodyLength^0.3800), digits = 1) #Оригинаяльная из статьи Ahn PMID 21874709

df$BrainBody <- round(df$brain/df$BodyWeight, digits = 4) #Отношение мозг:тело
df$HeatrBody <- round(df$heart/df$BodyWeight, digits = 4) #Отношение сердце:тело
df$LungBody <- round(df$lung/df$BodyWeight, digits = 4) #Отношение :тело
df$LiverBody <- round(df$liver/df$BodyWeight, digits = 4) #Отношение мозг:тело
df$SpleenBody <- round(df$spleen/df$BodyWeight, digits = 4) #Отношение мозг:тело
df$KidneyBody <- round(df$kidney/df$BodyWeight, digits = 4) #Отношение мозг:тело
df$ThymusBody <- round(df$thymus/df$BodyWeight, digits = 4) #Отношение мозг:тело
df$AdrenalBody <- round(df$adrenal/df$BodyWeight, digits = 4) #Отношение мозг:тело
df$PancreasBody <- round(df$pancreas/df$BodyWeight, digits = 4) #Отношение мозг:тело
df$PlacentaBody <- round(df$PlacentaWeight/df$BodyWeight, digits = 2) #Отношение мозг:тело




```

# Фильтр преполагаемого ЗРП(FGR) по массе мога и печени
```{r eval=FALSE, include=FALSE}
df$BrainLiverScore <- c(NA)

# Задаём счёт FGR по формуле (тонкий фильтр по неделям)
for (i in 1:nrow(df)) {
  if (df$gestation[i] <= 28 & df$BrainLiver[i] > 3.7) {
    df$BrainLiverScore[i] <- 1
  } else if (df$gestation[i] > 28 & df$BrainLiver[i] > 3.0) {
    df$BrainLiverScore[i] <- 1
  } else {
    df$BrainLiverScore[i] <- 0
  }
}


#Удаляем потенциальные FGR если BrainLiver удовлетворяет условиям (тонкий фильтр по неделям)
# removed_BrainLiver <- data.frame()
# df2 <- data.frame()
# 
# for (i in 1:nrow(df)) {
#   if (!is.na(df$gestation[i]) & !is.na(df$BrainLiver[i])) {
#     if (df$gestation[i] <= 28 & df$BrainLiver[i] > 3.7) {
#       removed_3_BrainLiver <- rbind(removed_3_BrainLiver, df[i,])
#       df <- df[-i,]
#     } else if (df$gestation[i] > 28 & df$BrainLiver[i] > 3.0) {
#       removed_3_BrainLiver <- rbind(removed_3_BrainLiver, df[i,])
#       df <- df[-i,]
#     } else {
#       df2 <- rbind(df2, df[i,])
#     }
#   }
# } 
```
